language: python
python:
  - "3"
  - "3.7"
  - "3.8"

env:
  - DJANGO_VERSION=3
  - DJANGO_VERSION=4

install:
  - pip install Django==$DJANGO_VERSION
  - python setup.py install

script: python manage.py test tests